version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2023
      POSTGRES_DB: postgres
      # Cambiamos PGDATA para que los datos se almacenen en pgdata/pgdata
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
      timeout: 5s

  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      - DATABASE_URL=postgresql://postgres:2023@db:5432/postgres
      - SOME_OTHER_ENV_VARIABLE=value
      - WATCHFILES_FORCE_POLLING=true

volumes:
  pgdata:
