"""validacion despues de modificacion de env.py

Revision ID: 142b1d9dbf86
Revises: 07a7ae25a127
Create Date: 2025-01-21 15:50:55.941965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '142b1d9dbf86'
down_revision: Union[str, None] = '07a7ae25a127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Created_dt', sa.DateTime(), nullable=False),
    sa.Column('Customer_PO', sa.String(length=50), nullable=False),
    sa.Column('DO', sa.String(length=50), nullable=False),
    sa.Column('customer', sa.String(length=50), nullable=False),
    sa.Column('City', sa.String(length=50), nullable=False),
    sa.Column('State', sa.String(length=50), nullable=False),
    sa.Column('Product_ID', sa.Integer(), nullable=False),
    sa.Column('Product_Qt', sa.Integer(), nullable=False),
    sa.Column('Appointment', sa.Date(), nullable=False),
    sa.Column('Appointment_hr', sa.Time(), nullable=False),
    sa.Column('Origin', sa.String(length=50), nullable=False),
    sa.Column('Order_status', sa.String(length=20), nullable=False),
    sa.Column('Delivered_dt', sa.DateTime(), nullable=True),
    sa.Column('POD', sa.Boolean(), nullable=True),
    sa.Column('Delivered_acc', sa.Integer(), nullable=True),
    sa.Column('Delivered_rch', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Customer_PO')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('FolioAmer', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ASSIGNED', 'IN_TRANSIT', 'DELIVERED', 'CANCELLED', 'CREATED', name='shipmentstatus'), nullable=True),
    sa.Column('vendor', sa.String(), nullable=True),
    sa.Column('origin', sa.String(), nullable=True),
    sa.Column('destination', sa.String(), nullable=True),
    sa.Column('customer', sa.String(), nullable=True),
    sa.Column('pickup_date', sa.DateTime(), nullable=True),
    sa.Column('delivery_date', sa.DateTime(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_id'), 'shipments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shipments_id'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_table('users')
    op.drop_table('Orders')
    # ### end Alembic commands ###
